/**
 * 费用相关的工具函数（已简化，业务逻辑已迁移到后端）
 */

import type { Project, Category } from './tauriApi';

/**
 * @deprecated 伙食补贴生成逻辑已迁移到后端 report_service
 * 此函数保留仅用于兼容性，请改用 reportApi.getProjectStatistics
 */
export function generateMealAllowanceRecords(
  project: Project | null, 
  categories: Category[]
): any[] {
  console.warn('generateMealAllowanceRecords 已废弃，请使用后端 API');
  return [];
}

/**
 * @deprecated 费用合并逻辑已不再需要
 * 此函数保留仅用于兼容性，请改用后端 API
 */
export function mergeExpenses(originalExpenses: any[], autoGeneratedExpenses: any[]): any[] {
  console.warn('mergeExpenses 已废弃，业务逻辑已迁移到后端');
  return originalExpenses;
}
