/**
 * 费用相关的工具函数
 */

/**
 * 生成伙食补贴记录
 * @param {Object} project - 项目对象
 * @param {Array} categories - 费用类别列表
 * @returns {Array} 生成的伙食补贴记录
 */
export function generateMealAllowanceRecords(project, categories) {
  if (!project || !project.start_date) return [];
  
  const records = [];
  const startDate = new Date(project.start_date);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  
  let endDate = today;
  if (project.end_date) {
    const projectEnd = new Date(project.end_date);
    projectEnd.setHours(0, 0, 0, 0);
    if (projectEnd < today) {
      endDate = projectEnd;
    }
  }
  
  // 查找是否存在伙食补贴类别
  const mealAllowanceCategory = categories.find(
    cat => cat.name === '伙食补贴'
  );
  
  if (!mealAllowanceCategory) {
    console.warn('未找到伙食补贴类别');
    return records;
  }
  
  // 计算天数并生成记录
  const timeDiff = endDate.getTime() - startDate.getTime();
  const daysCount = Math.ceil(timeDiff / (1000 * 3600 * 24)) + 1; // 包含开始当天
  
  for (let i = 0; i < daysCount; i++) {
    const currentDate = new Date(startDate);
    currentDate.setDate(startDate.getDate() + i);
    
    // 跳过超出项目结束日期的日期
    if (currentDate > endDate) break;
    
    const dateStr = currentDate.toISOString().split('T')[0];
    
    // 创建伙食补贴记录
    records.push({
      id: `meal_${project.id}_${dateStr}`, // 使用特殊ID标识自动生成的记录
      project_id: project.id,
      amount: 90,
      main_category_id: mealAllowanceCategory.id,
      main_category: mealAllowanceCategory,
      sub_category_id: null,
      sub_category: null,
      description: `伙食补贴 - ${dateStr}`,
      file_paths: [],
      date: dateStr,
      created_at: null,
      updated_at: null,
      voucher_types: [], // 伙食补贴默认无发票
      is_auto_generated: true // 标记为自动生成
    });
  }
  
  return records;
}

/**
 * 合并费用数据（原始费用+自动生成的费用）
 * @param {Array} originalExpenses - 原始费用数据
 * @param {Array} autoGeneratedExpenses - 自动生成的费用数据
 * @returns {Array} 合并后的费用数据
 */
export function mergeExpenses(originalExpenses, autoGeneratedExpenses) {
  return [...originalExpenses, ...autoGeneratedExpenses];
}